### PR TITLE
Fix missed adoption

### LINKED ISSUE #972: Unable to create 3 nodes cluster using match all criteria
## Description
Unable to create a 3 nodes cluster using match all criteria to select machine inventories.
Only 2 machine inventories are selected:

Image

## How to reproduce
Video:

https://github.com/user-attachments/assets/e3bf60d9-cbe7-4e44-b9c4-81fab7179a4a
 

## Env:
Rancher `v2.14.0-alpha9`
Elemental 1.9.0 from marketplace and also with the one from registry.suse.com

We already talked about it with @davidcassany and looks like a race condition, we can only reproduce it with this rancher version.
I haven't seen it with 2.11, 2.12 and 2.13

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes #972

### CODE REVIEW

File: controllers/machineselector_controller.go [hunk 1]
```diff
@@ -251,21 +251,21 @@ func (r *MachineInventorySelectorReconciler) findAndAdoptInventory(ctx context.C
...
 }
 
-func (r *MachineInventorySelectorReconciler) updateAdoptionStatus(ctx context.Context, miSelector *elementalv1.MachineInventorySelector, mInventory *elementalv1.MachineInventory) (bool, error) {
+func (r *MachineInventorySelectorReconciler) updateAdoptionStatus(ctx context.Context, miSelector *elementalv1.MachineInventorySelector, mInventory *elementalv1.MachineInventory) (time.Duration, error) {
 	logger := ctrl.LoggerFrom(ctx)
 
 	if miSelector.Status.MachineInventoryRef == nil {
 		logger.V(log.DebugDepth).Info("Waiting for a machine inventory match")
-		return false, nil
+		return time.Minute, nil
```
Comment (davidcassany) [inline controllers/machineselector_controller.go:259]: If we hit this case, let's ensure we re-trigger another attempt to find a match after a minute.

**Review by frelon — APPROVED** [review]
LGTM

**Comment by davidcassany** [comment]
Removed the last commit attempting to fix debug logging, as it was not really functional, so leaving logging as it was and keep only the commit to fix adoption and nothing else.
