### PR TITLE
Recover on syncer pod creation failures

### LINKED ISSUE #636: failed channel synchronization with k3s 1.27.10 and rancher 2.8.2
## Description

I was trying to bump the Kubernetes versions we use in the CI (https://github.com/rancher/elemental/pull/1216).
However, I hit an issue when I bumped the upstream cluster, `ManagedOSVersionChannel` failed to sync:
```
root@elemental-ja-chilve-rancher-server:~# kubectl get managedosversionchannel elemental-channel -n fleet-default -o yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  annotations:
    meta.helm.sh/release-name: elemental-operator
    meta.helm.sh/release-namespace: cattle-elemental-system
  creationTimestamp: "2024-02-19T09:03:43Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: elemental-channel
  namespace: fleet-default
  resourceVersion: "5063"
  uid: 5c710bf2-ea3f-43a7-886d-d21f28a45e7a
spec:
  options:
    image: registry.opensuse.org/isv/rancher/elemental/dev/containers/rancher/elemental-channel:1.5.0
  syncInterval: 1h
  type: custom
status:
  conditions:
  - lastTransitionTime: "2024-02-19T09:03:47Z"
    message: failed channel synchronization
    reason: FailedToSync
    status: "False"
    type: Ready
  lastSyncedTime: "2024-02-19T09:03:51Z"
```

## Env
Rancher stable  `2.8.2`
Elemental operator: dev =>  `registry.opensuse.org/isv/rancher/elemental/dev/containers/rancher/elemental-operator:1.5.0`
K3S used to host Rancher Manager: `v1.27.10+k3s2`

## How to reproduce
Install k3s v1.27.10+k3s2, Rancher manager 2.8.2, and elemental dev operator.

## Workaround
Modify the `syncInterval` and after, it syncs as expected.

Looks similar to https://github.com/rancher/elemental-operator/issues/577

## Operator's log
[elemental-operator.log](https://github.com/rancher/elemental-operator/files/14329943/elemental-operator.log)

### PR DESCRIPTION
**Pull request by anmazzotti**
Fixes  #636

### CODE REVIEW

**Review by davidcassany — APPROVED** [review]
LGTM

File: controllers/managedosversionchannel_controller.go [hunk 1]
```diff
@@ -177,7 +177,10 @@ func (r *ManagedOSVersionChannelReconciler) reconcile(ctx context.Context, manag
 	readyCondition := meta.FindStatusCondition(managedOSVersionChannel.Status.Conditions, elementalv1.ReadyCondition)
 	if readyCondition == nil {
 		// First reconcile loop does not have a ready condition
-		return ctrl.Result{}, r.createSyncerPod(ctx, managedOSVersionChannel, sync)
+		if err := r.createSyncerPod(ctx, managedOSVersionChannel, sync); err != nil {
+			return ctrl.Result{RequeueAfter: time.Second}, fmt.Errorf("creating syncer pod: %w", err)
+		}
+		return ctrl.Result{}, nil
```
Comment (davidcassany) [inline controllers/managedosversionchannel_controller.go:183]: After a closer look based on logs including this change I believe this changes has no real effect. On error the reconcile loop is always requeued, hence it was already requeued. Then the automatic requeue is eaten at line 184 so there aren't infinite requeues

Probably we could consider certain retries counter?
