### PR TITLE
Split chart into crds chart and operator chart

### LINKED ISSUE #438: elemental-operator installation sometimes fails
In the CI, we can see that the elemental-operator (dev) installation fails sporadically with this message:

```
msg: "[helm upgrade --install elemental-operator oci://registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart --namespace cattle-elemental-system --create-namespace] cmd, failed with the following error: Release \"elemental-operator\" does not exist.Installing it now.\nPulled: registry.opensuse.org/isv/rancher/elemental/dev/charts/rancher/elemental-operator-chart:1.2.2\nDigest: sha256:66f55a119c4ac7e3d5aed309b8510fd3288d4a027fef934b37a8e5b20b29f80e\nError: failed post-install: unable to build kubernetes object for deleting hook elemental-operator/templates/channel-hook.yaml: resource mapping not found for name: \"elemental-teal-channel\" namespace: \"fleet-default\" from \"\": no matches for kind \"ManagedOSVersionChannel\" in version \"elemental.cattle.io/v1beta1\"\nensure CRDs are installed first\n",
```

Failed job:
https://github.com/rancher/elemental/actions/runs/4887884892/jobs/8725003338

It also fails when the operator is uninstalled as well:
https://github.com/rancher/elemental/actions/runs/4889180147/jobs/8727492483

### PR DESCRIPTION
**Pull request by davidcassany**
Fixes #438

### CODE REVIEW

**Comment by davidcassany** [comment]
After trying with different approaches I think I found the procedure to migrate from a single chart to a dual chart approach (one exclusively for the crds and another one for all the rest). 

If we would simply split the charts as they are creating a new `elemental-operator-crds` chart I'd upgrade with the following procedure from the command line:

```bash

# To make sure the upgrade of the already existing chart does not delete the crds when upgrading
kubectl annotate crds -l release-name=elemental-operator -n cattle-elemental-operator helm.sh/resource-policy='keep' --overwrite=true

# To make sure elemental-operator-crds charts can adopt the orphaned cdrs after elemental-operator release upgrade
kubectl annotate crds -l release-name=elemental-operator -n cattle-elemental-operator meta.helm.sh/release-name='elemental-operator-crds' --overwrite=true

# During this upgrade instead of deleting the crds they  will be kept and orphaned thanks to the resource-policy annotation
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator oci://registry.opensuse.org/home/dcassany/elementaldev/charts/rancher/elemental-operator-chart

# This will adopt the already existing crds thanks to the updated release-name annotation
helm upgrade --create-namespace -n cattle-elemental-system --install elemental-operator-crds oci://registry.opensuse.org/home/dcassany/elementaldev/charts/rancher/elemental-operator-crds-chart
```

Since the annotation change is **strictly** required to prevent any data loss I thought of _coding_ those two annotations as part of a `pre-upgrade` helm hook. In particular there is a Job annotating these crds only on upgrades.

File: tests/e2e/config/config.go [hunk 1]
```diff
@@ -67,6 +70,9 @@ func ReadE2EConfig(configPath string) (*E2EConfig, error) { //nolint:gocyclo
 
 	if chart := os.Getenv("CHART"); chart != "" {
 		config.Chart = chart
+		dir, chartFile := filepath.Split(chart)
+		chartFile = strings.Replace(chartFile, "elemental-operator", "elemental-operator-crds", 1)
+		config.CRDsChart = filepath.Join(dir, chartFile)
```
Comment (davidcassany) [inline tests/e2e/config/config.go:75]: Something like this is how I'd adapt the elemental operator chart URI to _guess_ the crds chart.

The image reference:
`rancher/elemental-operator-chart` -> `rancher/elemental-operator-crds-chart`

The release name:
`elemental-operator` -> `elemental-operator-crds`

File: charts/operator/templates/pre-upgrade-hook.yaml [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+metadata:
+  name: {{ .Release.Name }}-helm-hook
+  annotations:
+    "helm.sh/hook": pre-upgrade
+    "helm.sh/hook-weight": "0"
+    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
+roleRef:
+  apiGroup: rbac.authorization.k8s.io
+  kind: ClusterRole
+  name: cattle-globalrole-admin
```
Comment (davidcassany) [inline charts/operator/templates/pre-upgrade-hook.yaml:22]: To annotate CRDs the job requires cluster admin role. Since crds are cluster wide I don't think there is any other alternative. I used this role as I assume this is present in any rancher installation.

File: charts/operator/templates/pre-upgrade-hook.yaml [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
+spec:
+  template:
+    metadata:
+      name: {{ .Release.Name }}-helm-hook
+    spec:
+      serviceAccountName: elemental-operator-helm-hook
+      containers:
+      - name: crd-keep-policy
+        image: rancher/kubectl:v1.24.13
```
Comment (davidcassany) [inline charts/operator/templates/pre-upgrade-hook.yaml:45]: I choose v1.24 as it is still maintained upstream during 2023

**Review by fgiudici — APPROVED** [review]
Great PR! Wasn't easy to deal with this 😅 
Still some doubts about the required inversion for the chart order installation in case of upgrade from the old operator, but as we discussed we may think about improving it in a follow-up PR if needed.
Few minor comments... we can address them in a follow-up PR too, no hurry.
Great work!

File: charts/operator/templates/pre-upgrade-hook.yaml [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+        command:
+          - "kubectl"
+          - "annotate"
+          - "crds"
+          - "--selector=release-name={{ .Release.Name }}"
+          - "--namespace={{ .Release.Namespace }}"
+          - "helm.sh/resource-policy=keep"
```
[the remark this answers is not in the document]
Comment (davidcassany) [reply charts/operator/templates/pre-upgrade-hook.yaml:52]: Yes, I was also wondering about that. As you say no big deal. This annotation is not honored on uninstall if it was not present as part of the installation (at least this is what I found in several helm issues). So the uninstall path is not affected.
